apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # Fix the IP and path to your NFS server
    server: 10.102.70.123
    path: "/var/lib/libvirt/images/hdd/nfs-share"